#!/bin/bash
git rm app/views/layouts/application.html.erb
git rm app/views/sessions/create.html.erb
git rm app/views/sessions/new.html.erb
git rm app/views/stories/_form.html.erb
git rm app/views/stories/_list.html.erb
git rm app/views/stories/edit.html.erb
git rm app/views/stories/index.html.erb
git rm app/views/stories/new.html.erb
git rm app/views/stories/show.html.erb
git rm app/views/users/_user_form.html.erb
git rm app/views/users/new.html.erb

